---

- name: slack | Notify sysadmins
  slack:
    msg: "_Rebooting *{{ inventory_hostname }}*_"
    token: "{{ slack_token }}"
    channel: "{{ slack_channel }}"
    username: "{{ slack_user }}"
    icon_emoji: "{{ slack_emoji }}"
  delegate_to: localhost
  when: 
    - packages.changed
    - ( 'linux-image' in kernelup.stdout )

- name: Rebooting
  become: true
  shell: ( /bin/sleep 4 ; shutdown -r now "Ansible installing a new linux kernel and other patches" ) &
  async: 30
  poll: 0
  ignore_errors: true
  changed_when: false
  when: 
    - packages.changed
    - ( 'linux-image' in kernelup.stdout )

- name: waiting for the server to become accessible
  wait_for:
    port: '{{ target_host_ssh_port }}'
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 60
    timeout: 3600
  connection: local
  when: 
    - packages.changed
    - ( 'linux-image' in kernelup.stdout )

- name: slack | Notify sysadmins
  slack:
    msg: "_Patching *{{ inventory_hostname }}* is complete_"
    token: "{{ slack_token }}"
    channel: "{{ slack_channel }}"
    username: "{{ slack_user }}"
    icon_emoji: "{{ slack_emoji }}"
  delegate_to: localhost

# Disabled post-patch Jira. Testing should be as automated as possible.
#- name: 'Creating a new Jira Task for Post-patching tests'
#  jira:
